//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagerIndependence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int ID { get; set; }
        public string loginAppleId { get; set; }
        public string loginPassword { get; set; }
        public string shippingUserLastName { get; set; }
        public string shippingUserFistName { get; set; }
        public string daytimePhoneAreaCode { get; set; }
        public string daytimePhone { get; set; }
        public string shippingUserStreet1 { get; set; }
        public string shippingUserStreet2 { get; set; }
        public string district { get; set; }
        public string postalCode { get; set; }
        public string wCount { get; set; }
        public string w1 { get; set; }
        public string w1detail { get; set; }
        public string w1Remark { get; set; }
        public string w2 { get; set; }
        public string w2detail { get; set; }
        public string w2Remark { get; set; }
        public string w3 { get; set; }
        public string w3detail { get; set; }
        public string w3Remark { get; set; }
        public string remarks { get; set; }
        public string cookies { get; set; }
        public string cancelUrl { get; set; }
    }
}
